### PR TITLE
New Idea - Video subtitle downloader

### PR DESCRIPTION
**Pull request by staticmanapp**
Dear human,

Here's a new entry for your approval. :tada:

Merge the pull request to accept it, or close it to send it away.

:heart: Your friend [Staticman](https://staticman.net) :muscle:

---
| Field        | Content                                                                                                                                                                                       |
| ------------ | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| status       | Ongoing                                                                                                                                                                                       |
| date_posted  | 2017-04-29                                                                                                                                                                                    |
| layout       | jobs                                                                                                                                                                                          |
| organization | Soumya Ranjan @GDG VIT                                                                                                                                                                        |
| org_url      | http://gdgvitvellore.com                                                                                                                                                                      |
| title        | Video subtitle downloader                                                                                                                                                                     |
| description  | As soon as we open a video on vlc or any other media player 
a python script checks if an existing subtitle file exists for the same if not it downloads it and stores it on the same folder |
| tags         | Web,python                                                                                                                                                                                    |
| date         | 2017-04-29T18:39:20.653Z                                                                                                                                                                      |

### CODE REVIEW

**Comment by soumya-ranjan7** [comment]
Interested soumya-ranjan7

**Comment by ayushpriya10** [comment]
Interested

**Comment by zacker-22** [comment]
Interested

**Comment by SuryaThiru** [comment]
Interested

**Comment by ashwini0529** [comment]
Check if anything like this already exists?

**Comment by UjjwalAyyangar** [comment]
@ashwini0529 - Something similar exists. 
Check this :- 
https://addons.videolan.org/p/1154045

**Comment by ashwini0529** [comment]
No point of doing that then.

**Pull request closed without merging**
