### PR TITLE
New Idea - Schizophrenia Social

### PR DESCRIPTION
**Pull request by staticmanapp**
Dear human,

Here's a new entry for your approval. :tada:

Merge the pull request to accept it, or close it to send it away.

:heart: Your friend [Staticman](https://staticman.net) :muscle:

---
| Field        | Content                                                                                                   |
| ------------ | --------------------------------------------------------------------------------------------------------- |
| status       | Ongoing                                                                                                   |
| date_posted  | 2017-05-25                                                                                                |
| layout       | jobs                                                                                                      |
| organization | Raina Garg @ GDG VIT Vellore                                                                              |
| org_url      | http://gdgvitvellore.com                                                                                  |
| title        | Schizophrenia Social                                                                                      |
| description  | The app/webapp helps Schizophrenic people to get over their social anxiety and helps diagnose them better |
| tags         | Android, Web                                                                                              |
| date         | 2017-05-25T08:32:05.723Z                                                                                  |

### CODE REVIEW

**Comment by hkedia321** [comment]
Interested

**Comment by apuayush** [comment]
interested

**Comment by gargraina03** [comment]
Interested

**Comment by initiator26** [comment]
Interested

**Pull request merged**
